[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]
live_config_reload = true

[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[window]
  option_as_alt="Both"
  opacity=0.85
  startup_mode="Windowed"
  decorations="None"
  blur=true
